### ISSUE TITLE
@tractr/nestjs-core prisma-filter does not handle all the prisma exceptions

### ISSUE THREAD

**Issue by maxmousse** [tractr/traxion#11]
**Describe the bug**
@tractr/nestjs-core prisma-filter does not handle all the prisma exceptions.

**Expected behavior**
The prisma exception filter must properly handle all prisma exceptions and return an adequate http response.

Should intercept some of the prisma error to send a good http status error

**Comment by floross** [comment]
[STAK-293]

[STAK-293]: https://tractr.atlassian.net/browse/STAK-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
