### ISSUE TITLE
Create docker registry push role for Github

### ISSUE THREAD

**Issue by EdouardDem** [tractr/traxion#117]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When creating a new projet, we have to manually create a role and an user that can push images on ECR and give its credentials to GitHub.

**Describe alternatives you've considered**
It could be done automatically by Terraform. At least the role creation.

**Comment by floross** [comment]
[STAK-242]

[STAK-242]: https://tractr.atlassian.net/browse/STAK-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
