### ISSUE TITLE
Hapify templates: Properly handle all hapify types and subtypes in generation

### ISSUE THREAD

**Issue by maxmousse** [tractr/traxion#13]
**Is your feature request related to a problem? Please describe.**
The hapify templates should handle all the types and subtypes available in hapify modelisation. Non handled types and features should be documented (add some validation with hapify validator).
Here is a list of the types actually handled: 
```
-> string
  xx default
  xx email
  xx password
  xx url
  -> text
  -> rich text

xx number
  -> integer
  -> float
  -> latitude
  -> longitude

-> datetime
  -> default
  -> date
  -> time

-> file
  ->image
  -> audio
  -> video
  -> document

xx entity
  xx 1to1
  xx 1toN
  -> Nto1
  xx NtoM

xx array
xx boolean
xx enum
-> object
```

**Comment by floross** [comment]
[STAK-294]

[STAK-294]: https://tractr.atlassian.net/browse/STAK-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
