### ISSUE TITLE
Angular Tools - Error Service

### ISSUE THREAD

**Issue by GlennTractr** [tractr/traxion#157]
Add error service in angular tools. 

Check if appVersion and appCode are necessary

**Comment by floross** [comment]
[STAK-236]

[STAK-236]: https://tractr.atlassian.net/browse/STAK-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
