### ISSUE TITLE
@tractr/hapify-templates-nestjs-models-common: Some services could be automatically mocked with jest

### ISSUE THREAD

**Issue by maxmousse** [tractr/traxion#16]
**Is your feature request related to a problem? Please describe.**
@tractr/hapify-templates-nestjs-models-common: Some services could be automatically mocked with jest: 
https://jestjs.io/docs/jest-object#jestcreatemockfrommodulemodulename

**Comment by floross** [comment]
[STAK-295]

[STAK-295]: https://tractr.atlassian.net/browse/STAK-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
