### ISSUE TITLE
String field should be searchable with partial match

### ISSUE THREAD

**Issue by maxmousse** [tractr/traxion#176]
**Is your feature request related to a problem? Please describe.** 
Currently, string search is only possible with full match for string fields

**Describe the solution you'd like** 
Filters should be added to allow string search with partial match

**Comment by floross** [comment]
[STAK-232]

[STAK-232]: https://tractr.atlassian.net/browse/STAK-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
