### ISSUE TITLE
[Models] Allow to inject in ModelsModule

### ISSUE THREAD

**Issue by GlennTractr** [tractr/traxion#251]
Actually ModelsModule not allow to inject external module/service.

**Comment by floross** [comment]
[STAK-181]

[STAK-181]: https://tractr.atlassian.net/browse/STAK-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
