### ISSUE TITLE
generated mock helpers does not handle unicity

### ISSUE THREAD

**Issue by maxmousse** [tractr/traxion#253]
**Describe the bug** A clear and concise description of what the bug is.

If a field is of type unique, the `mockModelFieldFactory` must return unique values.

**Comment by floross** [comment]
[STAK-180]

[STAK-180]: https://tractr.atlassian.net/browse/STAK-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
