### ISSUE TITLE
Logger module should accept a configuration for the loglevel

### ISSUE THREAD

**Issue by maxmousse** [tractr/traxion#272]
**Is your feature request related to a problem? Please describe.** A clear and
The `LoggerModule` of `@tractr/nestjs-core` does not accept a configuration to specify the log level that should be printed

**Describe the solution you'd like** A clear and concise description of what you
It must accept an array of log levels that should be printed.

**Comment by floross** [comment]
[STAK-297]

[STAK-297]: https://tractr.atlassian.net/browse/STAK-297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
