### ISSUE TITLE
Add cascade update and delete to the prisma schema

### ISSUE THREAD

**Issue by maxmousse** [tractr/traxion#274]
**Is your feature request related to a problem? Please describe.** A clear and
Last version of prisma handle cascade update and delete. It would be nice to migrate to the last version and add this to the prisma.schema templates

**Comment by maxmousse** [comment]
https://github.com/prisma/prisma/releases

**Comment by floross** [comment]
[STAK-298]

[STAK-298]: https://tractr.atlassian.net/browse/STAK-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
