### ISSUE TITLE
add Swagger plugin to nestjs apps

### ISSUE THREAD

**Issue by maxmousse** [tractr/traxion#275]
**Is your feature request related to a problem? Please describe.** A clear and
Last version of nx supports typescript plugins, allowing to add swagger plugin to nestjs apps (see the details here: https://blog.nrwl.io/micro-frontends-using-module-federation-presets-for-react-and-storybook-typescript-compiler-4120cf134816 )

Here is the documentation of the swagger plugin for nestjs: https://docs.nestjs.com/openapi/cli-plugin

**Comment by floross** [comment]
[STAK-298]

[STAK-298]: https://tractr.atlassian.net/browse/STAK-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
