### ISSUE TITLE
hapify validator must forbid fields of type file (and maybe object ?)

### ISSUE THREAD

**Issue by maxmousse** [tractr/traxion#279]
**Describe the bug** A clear and concise description of what the bug is.
In hapify, the fields of type `file` and `object` are not supported yet and must be forbid by the hapify validator in order to notify the developer in the hapify GUI.

**Comment by floross** [comment]
[STAK-294]

[STAK-294]: https://tractr.atlassian.net/browse/STAK-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
