### ISSUE TITLE
Hapify templates: fields of type `text` are not handled by the templates

### ISSUE THREAD

**Issue by maxmousse** [tractr/traxion#33]
**Describe the bug**
 Fields of type `text` are not handled by the templates, resulting in broken generated files

**To Reproduce**
Add a field with subtype `text` to modelisation.

**Expected behavior**
In a first time, the modelisation should throw an error if a type `text` is used, to avoid breaking the generated files.
In a seconde time, the type `text` should be handled by the templates.

**

**Comment by maxmousse** [comment]
The hapify validator has been updated to throw errors when `text` subtype is used. #34

**Comment by floross** [comment]
Duplicate of https://github.com/tractr/stack/issues/13
