### ISSUE TITLE
count controller method should be before findUnique

### ISSUE THREAD

**Issue by floross** [tractr/traxion#82]
**Describe the bug**
The count controller method should be before the findUnique method to not enter in the findUnique hook when we want to call count

**Additional context**
[https://github.com/tractr/stack/blob/73454dec43add15a2f6ea1d6d7d7609abcd8a1cb/packages/hapify-templates-nestjs-models-rest/hapify/generated/nestjs-models-rest/src/__kebab__/controllers/__kebab__.controller.ts.hpf#L97](https://github.com/tractr/stack/blob/73454dec43add15a2f6ea1d6d7d7609abcd8a1cb/packages/hapify-templates-nestjs-models-rest/hapify/generated/nestjs-models-rest/src/__kebab__/controllers/__kebab__.controller.ts.hpf#L97)

**Comment by maxmousse** [comment]
Closed by #84
